class AppData {
  static List currencyList = [
    {'currency': 'USD', 'name': 'US Dollar', 'flag': '🇺🇸'},
    {'currency': 'EUR', 'name': 'Euro', 'flag': '🇪🇺'},
    {'currency': 'JPY', 'name': 'Japanese Yen', 'flag': '🇯🇵'},
    {'currency': 'GBP', 'name': 'British Pound', 'flag': '🇬🇧'},
    {'currency': 'AUD', 'name': 'Australian Dollar', 'flag': '🇦🇺'},
    {'currency': 'CAD', 'name': 'Canadian Dollar', 'flag': '🇨🇦'},
    {'currency': 'CHF', 'name': 'Swiss Franc', 'flag': '🇨🇭'},
    {'currency': 'CNY', 'name': 'Chinese Yuan', 'flag': '🇨🇳'},
    {'currency': 'INR', 'name': 'Indian Rupee', 'flag': '🇮🇳'},
    {'currency': 'RUB', 'name': 'Russian Ruble', 'flag': '🇷🇺'},
    {'currency': 'BRL', 'name': 'Brazilian Real', 'flag': '🇧🇷'},
    {'currency': 'ZAR', 'name': 'South African Rand', 'flag': '🇿🇦'},
    {'currency': 'MXN', 'name': 'Mexican Peso', 'flag': '🇲🇽'},
    {'currency': 'SGD', 'name': 'Singapore Dollar', 'flag': '🇸🇬'},
    {'currency': 'HKD', 'name': 'Hong Kong Dollar', 'flag': '🇭🇰'},
    {'currency': 'NZD', 'name': 'New Zealand Dollar', 'flag': '🇳🇿'},
    {'currency': 'KRW', 'name': 'South Korean Won', 'flag': '🇰🇷'},
    {'currency': 'SEK', 'name': 'Swedish Krona', 'flag': '🇸🇪'},
    {'currency': 'NOK', 'name': 'Norwegian Krone', 'flag': '🇳🇴'},
    {'currency': 'DKK', 'name': 'Danish Krone', 'flag': '🇩🇰'},
    {'currency': 'TRY', 'name': 'Turkish Lira', 'flag': '🇹🇷'},
    {'currency': 'THB', 'name': 'Thai Baht', 'flag': '🇹🇭'},
    {'currency': 'MYR', 'name': 'Malaysian Ringgit', 'flag': '🇲🇾'},
    {'currency': 'PHP', 'name': 'Philippine Peso', 'flag': '🇵🇭'},
    {'currency': 'IDR', 'name': 'Indonesian Rupiah', 'flag': '🇮🇩'},
    {'currency': 'PLN', 'name': 'Polish Zloty', 'flag': '🇵🇱'},
    {'currency': 'CZK', 'name': 'Czech Koruna', 'flag': '🇨🇿'},
    {'currency': 'HUF', 'name': 'Hungarian Forint', 'flag': '🇭🇺'},
    {'currency': 'AED', 'name': 'United Arab Emirates Dirham', 'flag': '🇦🇪'},
    {'currency': 'SAR', 'name': 'Saudi Riyal', 'flag': '🇸🇦'},
    {'currency': 'EGP', 'name': 'Egyptian Pound', 'flag': '🇪🇬'},
    {'currency': 'ILS', 'name': 'Israeli New Shekel', 'flag': '🇮🇱'},
  ];
}
